import { Language } from "./types";

export const copy: Record<Language, Record<string, string>> = {
  hi: {
    appName: "Speak Yield",
    tagline: "बोलकर बेचें, बोलकर खरीदें",
    continue: "जारी रखें",
    sell: "बेचें",
    buy: "खरीदें",
    tapToSpeak: "बोलने के लिए दबाएँ",
    listening: "सुन रहा हूँ...",
    cancel: "रद्द करें",
    youSaid: "आपने कहा:",
    retry: "फिर से बोलें",
    confirm: "पुष्टि करें",
    readBack: "सुना रहा हूँ...",
    matched: "मिल गया!",
    confirmPayment: "भुगतान की पुष्टि करें",
    paymentDone: "भुगतान हो गया",
    netAmount: "कुल राशि",
    platformFee: "प्लेटफ़ॉर्म शुल्क",
    deliveryFee: "डिलीवरी शुल्क",
    done: "हो गया",
    delivery: "डिलीवरी",
    lowConfidence: "ठीक से सुनाई नहीं दिया, फिर कोशिश करें",
  },
  bn: {
    appName: "Speak Yield",
    tagline: "বলে বিক্রি করুন, বলে কিনুন",
    continue: "চালিয়ে যান",
    sell: "বিক্রি",
    buy: "কিনুন",
    tapToSpeak: "বলতে চাপুন",
    listening: "শুনছি...",
    cancel: "বাতিল করুন",
    youSaid: "আপনি বলেছেন:",
    retry: "আবার বলুন",
    confirm: "নিশ্চিত করুন",
    readBack: "শোনাচ্ছি...",
    matched: "মিলে গেছে!",
    confirmPayment: "পেমেন্ট নিশ্চিত করুন",
    paymentDone: "পেমেন্ট সম্পন্ন",
    netAmount: "মোট পরিমাণ",
    platformFee: "প্ল্যাটফর্ম ফি",
    deliveryFee: "ডেলিভারি ফি",
    done: "সম্পন্ন",
    delivery: "ডেলিভারি",
    lowConfidence: "ঠিকমতো শোনা যায়নি, আবার চেষ্টা করুন",
  },
  en: {
    appName: "Speak Yield",
    tagline: "Speak to sell, speak to buy",
    continue: "Continue",
    sell: "Sell",
    buy: "Buy",
    tapToSpeak: "Tap to speak",
    listening: "Listening...",
    cancel: "Cancel",
    youSaid: "You said:",
    retry: "Retry",
    confirm: "Confirm",
    readBack: "Playing read-back...",
    matched: "Matched!",
    confirmPayment: "Confirm Payment",
    paymentDone: "Payment done",
    netAmount: "Net amount",
    platformFee: "Platform fee",
    deliveryFee: "Delivery fee",
    done: "Done",
    delivery: "Delivery",
    lowConfidence: "Didn't catch that, try again",
  },
};
