import { Language } from "./types";

export const copy: Record<Language, Record<string, string>> = {
  hi: {
    appName: "Speak Yield",
    tagline: "बोलकर बेचें, बोलकर खरीदें",
    continue: "जारी रखें",
    sell: "बेचें",
    buy: "खरीदें",
    tapToSpeak: "बोलने के लिए दबाएँ",
    // Not "सुन रहा हूँ" / "समझ रहा हूँ" — a first-person AI narrating its own thinking is
    // what made this read as an assistant. State the market action, not the system's mind.
    listening: "बोलिए",
    understanding: "रिकॉर्ड हो रहा है",
    keepSpeaking: "बोलते रहें, रुकने पर अपने‑आप आगे बढ़ेगा",
    cancel: "रद्द करें",
    youSaid: "सुना:",
    retry: "फिर से बोलें",
    confirm: "पुष्टि करें",
    readBack: "पर्ची पढ़ी जा रही है",
    slipSell: "बिक्री पर्ची",
    slipBuy: "खरीद पर्ची",
    slipNo: "पर्ची नं.",
    slipNotFinal: "अभी पक्का नहीं हुआ",
    slipCommodity: "माल",
    slipQuantity: "मात्रा",
    slipRate: "भाव",
    slipPlace: "जगह",
    matched: "मिल गया!",
    confirmPayment: "आगे बढ़ें",
    paymentDone: "पक्का हो गया",
    netAmount: "कुल राशि",
    platformFee: "प्लेटफ़ॉर्म शुल्क",
    deliveryFee: "डिलीवरी शुल्क",
    done: "हो गया",
    delivery: "डिलीवरी",
    lowConfidence: "ठीक से सुनाई नहीं दिया, फिर कोशिश करें",
    marketPrice: "बाज़ार भाव",
    notSet: "नहीं बताया",
    chooseSell: "किसे बेचें, आप चुनें",
    chooseBuy: "किससे खरीदें, आप चुनें",
    priceHintSell: "आपने भाव नहीं बताया — ये खरीदार इस भाव पर ले रहे हैं",
    priceHintBuy: "आपने भाव नहीं बताया — ये दुकानें इस भाव पर दे रही हैं",
    reviewsWord: "समीक्षाएँ",
    kmAway: "किमी दूर",
    tagBestPriceSell: "सबसे अच्छा भाव",
    tagBestPriceBuy: "सबसे सस्ता",
    tagNearest: "सबसे पास",
    tagTopRated: "सबसे भरोसेमंद",
    choose: "यही चुनें",
    selected: "चुना गया",
    reviewTitle: "सौदा कैसा रहा?",
    reviewSubtitle: "को रेटिंग दें",
    reviewCommentHint: "कुछ कहना चाहें तो (ज़रूरी नहीं)",
    submitReview: "रेटिंग भेजें",
    skip: "छोड़ें",
    thanksReview: "आपकी राय के लिए धन्यवाद",
    tapToAnswer: "जवाब बोलने के लिए दबाएँ",
    promptWelcome: "अपनी भाषा बोलें — हिंदी, बांग्ला, या अंग्रेज़ी",
    promptConfirm: "क्या यह सही है? हाँ कहें या फिर से बोलें",
    promptChooseSell: "किसे बेचना है? नाम बोलें या पहला, दूसरा कहें",
    promptChooseBuy: "किससे खरीदना है? नाम बोलें या पहला, दूसरा कहें",
    promptPay: "आगे बढ़ने के लिए हाँ कहें",
    promptDone: "पूरा हुआ। घर जाने के लिए हो गया कहें",
    promptReview: "कितने तारे? एक से पाँच बोलें, या छोड़ें कहें",
    tabMarket: "बाज़ार",
    tabDeals: "मेरे सौदे",
    tabRates: "भाव",
    tabProfile: "मैं",
    todayRates: "आज के भाव",
    liveDemand: "अभी कौन खरीद रहा है",
    buyersTaking: "{n} खरीदार ले रहे हैं",
    priceRange: "₹{min} से ₹{max}",
    mandiRate: "मंडी भाव",
    sellThis: "यह बेचें",
    speakToTrade: "बोलकर सौदा करें",
    marketLoading: "बाज़ार खुल रहा है",
    marketError: "बाज़ार अभी नहीं खुला — फिर कोशिश करें",
    activeDeal: "चालू सौदा",
    perUnitShort: "/किलो",
    profileLanguage: "भाषा",
    profileLocation: "जगह",
    profileRole: "भूमिका",
    roleFarmer: "किसान",
    changeLanguage: "भाषा बदलें",
    earnedThisMonth: "इस महीने कमाए",
    dealsCount: "{n} सौदे",
    noDeals: "अभी कोई सौदा नहीं — बोलकर पहला सौदा करें",
    liveDeals: "चालू",
    pastDeals: "पूरे हुए",
    // Loading copy names the market action in progress — never the system's own thinking.
    loadingDraft: "आपकी पर्ची बन रही है",
    loadingBuyers: "खरीदार खोजे जा रहे हैं",
    loadingConfirming: "सौदा पक्का हो रहा है",
    biddingSell: "{n} खरीदार आपकी फ़सल पर बोली लगा रहे हैं",
    biddingBuy: "{n} दुकानें यह सामान दे रही हैं",
    spreadLabel: "भाव की रेंज",
    aboveMandi: "मंडी भाव से ₹{d} ज़्यादा",
    belowMandi: "मंडी भाव से ₹{d} कम",
    atMandi: "मंडी भाव के बराबर",
    seeBuyerPhone: "खरीदार का फ़ोन देखें",
    seeDealerPhone: "दुकान का फ़ोन देखें",
    buyerPhoneBanner: "यही सौदा — खरीदार की तरफ़ से",
    dealerPhoneBanner: "यही सौदा — दुकान की तरफ़ से",
    buyerAppName: "Speak Yield · व्यापारी",
    newOffer: "नई पेशकश",
    fromFarmer: "किसान",
    totalValue: "कुल",
    acceptOffer: "स्वीकार करें",
    declineOffer: "मना करें",
    offerAccepted: "स्वीकार कर लिया",
    backToFarmer: "किसान के फ़ोन पर लौटें",
    orderNo: "सौदा नं.",
    settledUpi: "UPI से निपटान",
    gstNote: "GST चालान व्हाट्सऐप पर भेजा गया",
    verified: "सत्यापित",
    // --- Mandi board ---
    boardUpdated: "{time} पर लिखा गया",
    sessionOpen: "खुली · {time} तक",
    sessionClosed: "बंद · {time} से",
    colRate: "भाव",
    colChange: "बदलाव",
    colArrivals: "आवक",
    dayRange: "दिन ₹{low}–{high}",
    arrivalsQtl: "{n} क्विं",
    weekTrend: "7 दिन",
    fullBoard: "पूरा बोर्ड",
    mandiFeed: "मंडी में अभी",
    justNow: "अभी",
    minutesAgo: "{n} मिनट पहले",
    hoursAgo: "{n} घंटे पहले",
    offline: "इंटरनेट नहीं — भाव पुराने हो सकते हैं",
    refresh: "ताज़ा करें",
    firstTimeHint: "बोलकर शुरू करें — “पचास किलो टमाटर बेचना है”",
    gotIt: "समझ गया",
    yourLedger: "आपका खाता",
    logout: "लॉग आउट",
    intentLabel: "मुझे करना है",
    profilePayment: "भुगतान",
    paymentUpi: "UPI · तुरंत",
    ratePerUnit: "₹{price} प्रति {unit}",
    yourPriceSell: "आपका भाव ₹{p} — ये खरीदार इस भाव पर ले रहे हैं",
    yourPriceBuy: "आपका भाव ₹{p} — ये दुकानें इस भाव पर दे रही हैं",
    // --- Buy side of the market ---
    // The dashboard turns to face the other direction: the same mandi, but now the
    // farmer is the one holding money. Nothing here calls them a customer — they are
    // still the farmer, buying what the next crop needs.
    liveSupply: "पास में कौन दे रहा है",
    dealersStocking: "{n} दुकानें",
    buyThis: "यह खरीदें",
    nearestDealer: "सबसे पास {d} किमी",
    lowestPrice: "सबसे सस्ता ₹{p}",
    noSupply: "पास में अभी कोई दुकान नहीं मिली",
    spentThisMonth: "इस महीने खर्च",
    ordersCount: "{n} खरीद",
    filterAll: "सब",
    exampleSell: "जैसे — “पचास किलो टमाटर बेचना है”",
    exampleBuy: "जैसे — “दो बोरी यूरिया चाहिए”",
  },
  bn: {
    appName: "Speak Yield",
    tagline: "বলে বিক্রি করুন, বলে কিনুন",
    continue: "চালিয়ে যান",
    sell: "বিক্রি",
    buy: "কিনুন",
    tapToSpeak: "বলতে চাপুন",
    listening: "বলুন",
    understanding: "রেকর্ড হচ্ছে",
    keepSpeaking: "বলতে থাকুন, থামলে নিজে থেকেই এগোবে",
    cancel: "বাতিল করুন",
    youSaid: "শোনা গেছে:",
    retry: "আবার বলুন",
    confirm: "নিশ্চিত করুন",
    readBack: "রসিদ পড়ে শোনানো হচ্ছে",
    slipSell: "বিক্রয় রসিদ",
    slipBuy: "ক্রয় রসিদ",
    slipNo: "রসিদ নং",
    slipNotFinal: "এখনো পাকা হয়নি",
    slipCommodity: "মাল",
    slipQuantity: "পরিমাণ",
    slipRate: "দর",
    slipPlace: "জায়গা",
    matched: "মিলে গেছে!",
    confirmPayment: "এগিয়ে যান",
    paymentDone: "সম্পন্ন হয়েছে",
    netAmount: "মোট পরিমাণ",
    platformFee: "প্ল্যাটফর্ম ফি",
    deliveryFee: "ডেলিভারি ফি",
    done: "সম্পন্ন",
    delivery: "ডেলিভারি",
    lowConfidence: "ঠিকমতো শোনা যায়নি, আবার চেষ্টা করুন",
    marketPrice: "বাজার দর",
    notSet: "বলা হয়নি",
    chooseSell: "কাকে বিক্রি করবেন, বেছে নিন",
    chooseBuy: "কার থেকে কিনবেন, বেছে নিন",
    priceHintSell: "আপনি দর বলেননি — এই ক্রেতারা এই দরে নিচ্ছে",
    priceHintBuy: "আপনি দর বলেননি — এই দোকানগুলো এই দরে দিচ্ছে",
    reviewsWord: "রিভিউ",
    kmAway: "কিমি দূরে",
    tagBestPriceSell: "সেরা দর",
    tagBestPriceBuy: "সবচেয়ে সস্তা",
    tagNearest: "সবচেয়ে কাছে",
    tagTopRated: "সবচেয়ে বিশ্বস্ত",
    choose: "এটাই বেছে নিন",
    selected: "নির্বাচিত",
    reviewTitle: "লেনদেন কেমন হলো?",
    reviewSubtitle: "কে রেটিং দিন",
    reviewCommentHint: "কিছু বলতে চাইলে (ঐচ্ছিক)",
    submitReview: "রেটিং পাঠান",
    skip: "বাদ দিন",
    thanksReview: "আপনার মতামতের জন্য ধন্যবাদ",
    tapToAnswer: "উত্তর বলতে চাপুন",
    promptWelcome: "আপনার ভাষা বলুন — হিন্দি, বাংলা, বা ইংরেজি",
    promptConfirm: "এটা কি ঠিক আছে? হ্যাঁ বলুন বা আবার বলুন",
    promptChooseSell: "কাকে বিক্রি করবেন? নাম বলুন বা প্রথম, দ্বিতীয় বলুন",
    promptChooseBuy: "কার থেকে কিনবেন? নাম বলুন বা প্রথম, দ্বিতীয় বলুন",
    promptPay: "এগিয়ে যেতে হ্যাঁ বলুন",
    promptDone: "সম্পন্ন। বাড়ি যেতে হয়ে গেছে বলুন",
    promptReview: "কত তারা? এক থেকে পাঁচ বলুন, বা বাদ দিন বলুন",
    tabMarket: "বাজার",
    tabDeals: "আমার সওদা",
    tabRates: "দর",
    tabProfile: "আমি",
    todayRates: "আজকের দর",
    liveDemand: "এখন কারা কিনছে",
    buyersTaking: "{n} জন ক্রেতা নিচ্ছে",
    priceRange: "₹{min} থেকে ₹{max}",
    mandiRate: "বাজার দর",
    sellThis: "এটা বিক্রি করুন",
    speakToTrade: "বলে সওদা করুন",
    marketLoading: "বাজার খুলছে",
    marketError: "বাজার এখন খোলেনি — আবার চেষ্টা করুন",
    activeDeal: "চলতি সওদা",
    perUnitShort: "/কেজি",
    profileLanguage: "ভাষা",
    profileLocation: "জায়গা",
    profileRole: "ভূমিকা",
    roleFarmer: "কৃষক",
    changeLanguage: "ভাষা বদলান",
    earnedThisMonth: "এই মাসে আয়",
    dealsCount: "{n} সওদা",
    noDeals: "এখনো কোনো সওদা নেই — বলে প্রথম সওদা করুন",
    liveDeals: "চলছে",
    pastDeals: "সম্পন্ন",
    loadingDraft: "আপনার রসিদ তৈরি হচ্ছে",
    loadingBuyers: "ক্রেতা খোঁজা হচ্ছে",
    loadingConfirming: "সওদা পাকা হচ্ছে",
    biddingSell: "{n} জন ক্রেতা আপনার ফসলে দর দিচ্ছে",
    biddingBuy: "{n} টি দোকান এই মাল দিচ্ছে",
    spreadLabel: "দরের সীমা",
    aboveMandi: "বাজার দরের চেয়ে ₹{d} বেশি",
    belowMandi: "বাজার দরের চেয়ে ₹{d} কম",
    atMandi: "বাজার দরের সমান",
    seeBuyerPhone: "ক্রেতার ফোন দেখুন",
    seeDealerPhone: "দোকানের ফোন দেখুন",
    buyerPhoneBanner: "একই সওদা — ক্রেতার দিক থেকে",
    dealerPhoneBanner: "একই সওদা — দোকানের দিক থেকে",
    buyerAppName: "Speak Yield · ব্যবসায়ী",
    newOffer: "নতুন প্রস্তাব",
    fromFarmer: "কৃষক",
    totalValue: "মোট",
    acceptOffer: "গ্রহণ করুন",
    declineOffer: "প্রত্যাখ্যান",
    offerAccepted: "গ্রহণ করা হয়েছে",
    backToFarmer: "কৃষকের ফোনে ফিরুন",
    orderNo: "সওদা নং",
    settledUpi: "UPI-তে নিষ্পত্তি",
    gstNote: "GST চালান হোয়াটসঅ্যাপে পাঠানো হয়েছে",
    verified: "যাচাই করা",
    // --- Mandi board ---
    boardUpdated: "{time}-এ লেখা",
    sessionOpen: "খোলা · {time} পর্যন্ত",
    sessionClosed: "বন্ধ · {time} থেকে",
    colRate: "দর",
    colChange: "বদল",
    colArrivals: "আমদানি",
    dayRange: "দিন ₹{low}–{high}",
    arrivalsQtl: "{n} কুই",
    weekTrend: "৭ দিন",
    fullBoard: "পুরো বোর্ড",
    mandiFeed: "বাজারে এখন",
    justNow: "এইমাত্র",
    minutesAgo: "{n} মিনিট আগে",
    hoursAgo: "{n} ঘণ্টা আগে",
    offline: "ইন্টারনেট নেই — দর পুরনো হতে পারে",
    refresh: "নতুন করে দেখুন",
    firstTimeHint: "বলে শুরু করুন — “পঞ্চাশ কেজি টমেটো বেচব”",
    gotIt: "বুঝেছি",
    yourLedger: "আপনার খাতা",
    logout: "লগ আউট",
    intentLabel: "আমি করতে চাই",
    profilePayment: "পেমেন্ট",
    paymentUpi: "UPI · তৎক্ষণাৎ",
    ratePerUnit: "₹{price} প্রতি {unit}",
    yourPriceSell: "আপনার দর ₹{p} — এই ক্রেতারা এই দরে নিচ্ছে",
    yourPriceBuy: "আপনার দর ₹{p} — এই দোকানগুলো এই দরে দিচ্ছে",
    // --- Buy side of the market ---
    liveSupply: "কাছে কারা দিচ্ছে",
    dealersStocking: "{n} টি দোকান",
    buyThis: "এটা কিনুন",
    nearestDealer: "সবচেয়ে কাছে {d} কিমি",
    lowestPrice: "সবচেয়ে সস্তা ₹{p}",
    noSupply: "কাছে এখন কোনও দোকান পাওয়া যায়নি",
    spentThisMonth: "এই মাসে খরচ",
    ordersCount: "{n} কেনা",
    filterAll: "সব",
    exampleSell: "যেমন — “পঞ্চাশ কেজি টমেটো বিক্রি করব”",
    exampleBuy: "যেমন — “দুই বস্তা ইউরিয়া লাগবে”",
  },
  en: {
    appName: "Speak Yield",
    tagline: "Speak to sell, speak to buy",
    continue: "Continue",
    sell: "Sell",
    buy: "Buy",
    tapToSpeak: "Tap to speak",
    listening: "Speak now",
    understanding: "Recording",
    keepSpeaking: "Keep speaking — it moves on when you stop",
    cancel: "Cancel",
    youSaid: "Heard:",
    retry: "Retry",
    confirm: "Confirm",
    readBack: "Reading the slip aloud",
    slipSell: "Sale slip",
    slipBuy: "Purchase slip",
    slipNo: "Slip no.",
    slipNotFinal: "Not committed yet",
    slipCommodity: "Item",
    slipQuantity: "Quantity",
    slipRate: "Rate",
    slipPlace: "Place",
    matched: "Matched!",
    confirmPayment: "Proceed",
    paymentDone: "All set",
    netAmount: "Net amount",
    platformFee: "Platform fee",
    deliveryFee: "Delivery fee",
    done: "Done",
    delivery: "Delivery",
    lowConfidence: "Didn't catch that, try again",
    marketPrice: "Market price",
    notSet: "Not set",
    chooseSell: "Choose who to sell to",
    chooseBuy: "Choose who to buy from",
    priceHintSell: "You didn't say a price — here's who's buying, and at what",
    priceHintBuy: "You didn't say a price — here's who's selling, and at what",
    reviewsWord: "reviews",
    kmAway: "km away",
    tagBestPriceSell: "Best price",
    tagBestPriceBuy: "Lowest price",
    tagNearest: "Nearest",
    tagTopRated: "Top rated",
    choose: "Choose this",
    selected: "Selected",
    reviewTitle: "How was this deal?",
    reviewSubtitle: "Rate",
    reviewCommentHint: "Add a note (optional)",
    submitReview: "Submit rating",
    skip: "Skip",
    thanksReview: "Thanks for your feedback",
    tapToAnswer: "Tap to answer",
    promptWelcome: "Say your language — Hindi, Bengali, or English",
    promptConfirm: "Is this correct? Say yes, or say it again",
    promptChooseSell: "Who to sell to? Say a name, or say first, second",
    promptChooseBuy: "Who to buy from? Say a name, or say first, second",
    promptPay: "Say yes to go ahead",
    promptDone: "All done. Say done to go home",
    promptReview: "How many stars? Say one to five, or say skip",
    tabMarket: "Market",
    tabDeals: "My deals",
    tabRates: "Rates",
    tabProfile: "Me",
    todayRates: "Today's rates",
    liveDemand: "Who's buying right now",
    buyersTaking: "{n} buyers taking it",
    priceRange: "₹{min} to ₹{max}",
    mandiRate: "Mandi rate",
    sellThis: "Sell this",
    speakToTrade: "Speak to trade",
    marketLoading: "Opening the market",
    marketError: "Market didn't open — try again",
    activeDeal: "Active deal",
    perUnitShort: "/kg",
    profileLanguage: "Language",
    profileLocation: "Location",
    profileRole: "Role",
    roleFarmer: "Farmer",
    changeLanguage: "Change language",
    earnedThisMonth: "Earned this month",
    dealsCount: "{n} deals",
    noDeals: "No deals yet — speak your first one",
    liveDeals: "Live",
    pastDeals: "Completed",
    loadingDraft: "Preparing your slip",
    loadingBuyers: "Finding buyers",
    loadingConfirming: "Locking in the deal",
    biddingSell: "{n} buyers bidding on your crop",
    biddingBuy: "{n} shops supplying this",
    spreadLabel: "Price range",
    aboveMandi: "₹{d} above mandi rate",
    belowMandi: "₹{d} below mandi rate",
    atMandi: "Same as mandi rate",
    seeBuyerPhone: "See the buyer's phone",
    seeDealerPhone: "See the shop's phone",
    buyerPhoneBanner: "The same deal — from the buyer's side",
    dealerPhoneBanner: "The same deal — from the shop's side",
    buyerAppName: "Speak Yield · Trader",
    newOffer: "New offer",
    fromFarmer: "Farmer",
    totalValue: "Total",
    acceptOffer: "Accept",
    declineOffer: "Decline",
    offerAccepted: "Accepted",
    backToFarmer: "Back to the farmer's phone",
    orderNo: "Deal no.",
    settledUpi: "Settled via UPI",
    gstNote: "GST invoice sent on WhatsApp",
    verified: "Verified",
    // --- Mandi board ---
    boardUpdated: "Chalked at {time}",
    sessionOpen: "Open · till {time}",
    sessionClosed: "Closed · opens {time}",
    colRate: "Rate",
    colChange: "Chg",
    colArrivals: "Arrivals",
    dayRange: "Day ₹{low}–{high}",
    arrivalsQtl: "{n} qtl",
    weekTrend: "7d",
    fullBoard: "Full board",
    mandiFeed: "Happening in the mandi",
    justNow: "just now",
    minutesAgo: "{n} min ago",
    hoursAgo: "{n} hr ago",
    offline: "No connection — rates may be stale",
    refresh: "Refresh",
    firstTimeHint: "Start by speaking — “sell fifty kilos of tomato”",
    gotIt: "Got it",
    yourLedger: "Your ledger",
    logout: "Log out",
    intentLabel: "I want to",
    profilePayment: "Payment",
    paymentUpi: "UPI · instant",
    ratePerUnit: "₹{price} per {unit}",
    yourPriceSell: "Your price ₹{p} — here's who's buying, and at what",
    yourPriceBuy: "Your price ₹{p} — here's who's selling, and at what",
    // --- Buy side of the market ---
    liveSupply: "Who's selling near you",
    // Kept short: the input name shares this row and "Urea fertiliser" is already long.
    dealersStocking: "{n} dealers",
    buyThis: "Buy this",
    nearestDealer: "nearest {d} km",
    lowestPrice: "lowest ₹{p}",
    noSupply: "No dealers listed near you right now",
    spentThisMonth: "Spent this month",
    ordersCount: "{n} purchases",
    filterAll: "All",
    exampleSell: "Like — “sell fifty kilos of tomato”",
    exampleBuy: "Like — “I need two bags of urea”",
  },
};

/** Fill `{placeholder}` slots in a copy string: `fill(t.buyersTaking, { n: 4 })`. */
export function fill(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (match, key) =>
    key in values ? String(values[key]) : match,
  );
}

/** The commodity name in the farmer's language, falling back to the English label. */
export function commodityName(
  item: { commodity: string; nameHi: string; nameBn: string },
  language: Language,
): string {
  if (language === "hi") return item.nameHi || item.commodity;
  if (language === "bn") return item.nameBn || item.commodity;
  return item.commodity;
}
