import { Language } from "./types";

export const copy: Record<Language, Record<string, string>> = {
  hi: {
    appName: "Speak Yield",
    tagline: "बोलकर बेचें, बोलकर खरीदें",
    continue: "जारी रखें",
    sell: "बेचें",
    buy: "खरीदें",
    tapToSpeak: "बोलने के लिए दबाएँ",
    listening: "सुन रहा हूँ...",
    understanding: "समझ रहा हूँ...",
    keepSpeaking: "बोलते रहें, रुकने पर अपने‑आप आगे बढ़ेगा",
    cancel: "रद्द करें",
    youSaid: "आपने कहा:",
    retry: "फिर से बोलें",
    confirm: "पुष्टि करें",
    readBack: "सुना रहा हूँ...",
    matched: "मिल गया!",
    confirmPayment: "आगे बढ़ें",
    paymentDone: "पक्का हो गया",
    netAmount: "कुल राशि",
    platformFee: "प्लेटफ़ॉर्म शुल्क",
    deliveryFee: "डिलीवरी शुल्क",
    done: "हो गया",
    delivery: "डिलीवरी",
    lowConfidence: "ठीक से सुनाई नहीं दिया, फिर कोशिश करें",
    marketPrice: "बाज़ार भाव",
    notSet: "नहीं बताया",
    chooseSell: "किसे बेचें, आप चुनें",
    chooseBuy: "किससे खरीदें, आप चुनें",
    priceHintSell: "आपने भाव नहीं बताया — ये खरीदार इस भाव पर ले रहे हैं",
    priceHintBuy: "आपने भाव नहीं बताया — ये दुकानें इस भाव पर दे रही हैं",
    reviewsWord: "समीक्षाएँ",
    kmAway: "किमी दूर",
    tagBestPriceSell: "सबसे अच्छा भाव",
    tagBestPriceBuy: "सबसे सस्ता",
    tagNearest: "सबसे पास",
    tagTopRated: "सबसे भरोसेमंद",
    choose: "यही चुनें",
    selected: "चुना गया",
    reviewTitle: "सौदा कैसा रहा?",
    reviewSubtitle: "को रेटिंग दें",
    reviewCommentHint: "कुछ कहना चाहें तो (ज़रूरी नहीं)",
    submitReview: "रेटिंग भेजें",
    skip: "छोड़ें",
    thanksReview: "आपकी राय के लिए धन्यवाद",
    tapToAnswer: "जवाब बोलने के लिए दबाएँ",
    promptWelcome: "अपनी भाषा बोलें — हिंदी, बांग्ला, या अंग्रेज़ी",
    promptConfirm: "क्या यह सही है? हाँ कहें या फिर से बोलें",
    promptChooseSell: "किसे बेचना है? नाम बोलें या पहला, दूसरा कहें",
    promptChooseBuy: "किससे खरीदना है? नाम बोलें या पहला, दूसरा कहें",
    promptPay: "आगे बढ़ने के लिए हाँ कहें",
    promptDone: "पूरा हुआ। घर जाने के लिए हो गया कहें",
    promptReview: "कितने तारे? एक से पाँच बोलें, या छोड़ें कहें",
  },
  bn: {
    appName: "Speak Yield",
    tagline: "বলে বিক্রি করুন, বলে কিনুন",
    continue: "চালিয়ে যান",
    sell: "বিক্রি",
    buy: "কিনুন",
    tapToSpeak: "বলতে চাপুন",
    listening: "শুনছি...",
    understanding: "বুঝছি...",
    keepSpeaking: "বলতে থাকুন, থামলে নিজে থেকেই এগোবে",
    cancel: "বাতিল করুন",
    youSaid: "আপনি বলেছেন:",
    retry: "আবার বলুন",
    confirm: "নিশ্চিত করুন",
    readBack: "শোনাচ্ছি...",
    matched: "মিলে গেছে!",
    confirmPayment: "এগিয়ে যান",
    paymentDone: "সম্পন্ন হয়েছে",
    netAmount: "মোট পরিমাণ",
    platformFee: "প্ল্যাটফর্ম ফি",
    deliveryFee: "ডেলিভারি ফি",
    done: "সম্পন্ন",
    delivery: "ডেলিভারি",
    lowConfidence: "ঠিকমতো শোনা যায়নি, আবার চেষ্টা করুন",
    marketPrice: "বাজার দর",
    notSet: "বলা হয়নি",
    chooseSell: "কাকে বিক্রি করবেন, বেছে নিন",
    chooseBuy: "কার থেকে কিনবেন, বেছে নিন",
    priceHintSell: "আপনি দর বলেননি — এই ক্রেতারা এই দরে নিচ্ছে",
    priceHintBuy: "আপনি দর বলেননি — এই দোকানগুলো এই দরে দিচ্ছে",
    reviewsWord: "রিভিউ",
    kmAway: "কিমি দূরে",
    tagBestPriceSell: "সেরা দর",
    tagBestPriceBuy: "সবচেয়ে সস্তা",
    tagNearest: "সবচেয়ে কাছে",
    tagTopRated: "সবচেয়ে বিশ্বস্ত",
    choose: "এটাই বেছে নিন",
    selected: "নির্বাচিত",
    reviewTitle: "লেনদেন কেমন হলো?",
    reviewSubtitle: "কে রেটিং দিন",
    reviewCommentHint: "কিছু বলতে চাইলে (ঐচ্ছিক)",
    submitReview: "রেটিং পাঠান",
    skip: "বাদ দিন",
    thanksReview: "আপনার মতামতের জন্য ধন্যবাদ",
    tapToAnswer: "উত্তর বলতে চাপুন",
    promptWelcome: "আপনার ভাষা বলুন — হিন্দি, বাংলা, বা ইংরেজি",
    promptConfirm: "এটা কি ঠিক আছে? হ্যাঁ বলুন বা আবার বলুন",
    promptChooseSell: "কাকে বিক্রি করবেন? নাম বলুন বা প্রথম, দ্বিতীয় বলুন",
    promptChooseBuy: "কার থেকে কিনবেন? নাম বলুন বা প্রথম, দ্বিতীয় বলুন",
    promptPay: "এগিয়ে যেতে হ্যাঁ বলুন",
    promptDone: "সম্পন্ন। বাড়ি যেতে হয়ে গেছে বলুন",
    promptReview: "কত তারা? এক থেকে পাঁচ বলুন, বা বাদ দিন বলুন",
  },
  en: {
    appName: "Speak Yield",
    tagline: "Speak to sell, speak to buy",
    continue: "Continue",
    sell: "Sell",
    buy: "Buy",
    tapToSpeak: "Tap to speak",
    listening: "Listening...",
    understanding: "Understanding...",
    keepSpeaking: "Keep speaking — it moves on when you stop",
    cancel: "Cancel",
    youSaid: "You said:",
    retry: "Retry",
    confirm: "Confirm",
    readBack: "Playing read-back...",
    matched: "Matched!",
    confirmPayment: "Proceed",
    paymentDone: "All set",
    netAmount: "Net amount",
    platformFee: "Platform fee",
    deliveryFee: "Delivery fee",
    done: "Done",
    delivery: "Delivery",
    lowConfidence: "Didn't catch that, try again",
    marketPrice: "Market price",
    notSet: "Not set",
    chooseSell: "Choose who to sell to",
    chooseBuy: "Choose who to buy from",
    priceHintSell: "You didn't say a price — here's who's buying, and at what",
    priceHintBuy: "You didn't say a price — here's who's selling, and at what",
    reviewsWord: "reviews",
    kmAway: "km away",
    tagBestPriceSell: "Best price",
    tagBestPriceBuy: "Lowest price",
    tagNearest: "Nearest",
    tagTopRated: "Top rated",
    choose: "Choose this",
    selected: "Selected",
    reviewTitle: "How was this deal?",
    reviewSubtitle: "Rate",
    reviewCommentHint: "Add a note (optional)",
    submitReview: "Submit rating",
    skip: "Skip",
    thanksReview: "Thanks for your feedback",
    tapToAnswer: "Tap to answer",
    promptWelcome: "Say your language — Hindi, Bengali, or English",
    promptConfirm: "Is this correct? Say yes, or say it again",
    promptChooseSell: "Who to sell to? Say a name, or say first, second",
    promptChooseBuy: "Who to buy from? Say a name, or say first, second",
    promptPay: "Say yes to go ahead",
    promptDone: "All done. Say done to go home",
    promptReview: "How many stars? Say one to five, or say skip",
  },
};
